
# 상품 정보 테이블
CREATE TABLE ITEM(
	ITEM_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ITEM_NAME VARCHAR(20) NOT NULL 
	, ITEM_PRICE INT NOT NULL 
	, REG_DATE DATETIME DEFAULT SYSDATE()
	, ITEM_INTRO VARCHAR(50)
);
SELECT * FROM ITEM; 
DELETE FROM ITEM WHERE ITEM_NUM = 1;

DELETE FROM ITEM;