CREATE TABLE SECURITY_MEMBER(
	MEM_EMAIL VARCHAR(100) PRIMARY KEY 
	, MEM_PW VARCHAR(100) NOT NULL
	, MEM_NAME VARCHAR(30) NOT NULL
	, MEM_ROLE VARCHAR(30) NOT NULL 	# ROLE_USER, ROLE_MANAGER, ROLE_ADMIN
	# 스프링 시큐리티에서 권한을 설정하려면 기본적으로 ROLE_ 이 들어가야함
);

DROP TABLE SECURITY_MEMBER;
SELECT * FROM SECURITY_MEMBER;