
###### 도서 쇼핑몰 프로젝트 테이블 생성 SQL #####

### 생성 예상 테이블 ###
#1. 회원 정보 테이블 SHOP_MEMBER
#2. 도서 카테고리 테이블 BOOK_CATEGORY
#3. 도서 정보 테이블 SHOP_BOOK
#4. 장바구니 테이블 SHOP_CART
#5. 구매 정보 테이블 SHOP_BUY

# 회원정보 테이블 생성문
CREATE TABLE SHOP_MEMBER (
	MEM_EMAIL VARCHAR(50) PRIMARY KEY 
	, MEM_PW VARCHAR(50) NOT NULL 
	, MEM_NAME VARCHAR(30) NOT NULL 
	, MEM_TEL VARCHAR(15) NOT NULL UNIQUE  #'010-1111-2222'
	, MEM_ADDR VARCHAR(50)
	, ADDR_DETAIL VARCHAR(100)
	, IS_USING VARCHAR(10) DEFAULT 'Y'  #'Y' : 사용중, 'N' : 사용 안 함
	, MEM_ROLE VARCHAR(20) DEFAULT 'USER' #USER:회원, MANAGER:쇼핑몰 운영자, ADMIN:관리자
	, JOIN_DATE DATETIME DEFAULT SYSDATE()
);


# 도서 카테고리 정보
CREATE TABLE BOOK_CATEGORY (
	CATE_NUM INT PRIMARY KEY AUTO_INCREMENT
	, CATE_NAME VARCHAR(20) NOT NULL UNIQUE 
);

# 도서 카테고리 기본 데이터
INSERT INTO BOOK_CATEGORY VALUES (1,'IT/인터넷');
INSERT INTO BOOK_CATEGORY VALUES (2,'자기계발');
INSERT INTO BOOK_CATEGORY VALUES (3,'소설/에세이');


# 도서 정보 테이블
CREATE TABLE SHOP_BOOK (
	BOOK_NUM INT PRIMARY KEY AUTO_INCREMENT
	, BOOK_TITLE VARCHAR(30) NOT NULL
	, AUTHOR VARCHAR(20) NOT NULL
	, BOOK_PRICE INT NOT NULL
	, BOOK_STOCK INT DEFAULT 10
	, BOOK_INTRO VARCHAR(200)
	, PUBLISH_DATE DATETIME
	, CATE_NUM INT NOT NULL REFERENCES BOOK_CATEGORY (CATE_NUM)
);

# 도서 이미지 정보 테이블
CREATE TABLE BOOK_IMG(
	IMG_NUM INT PRIMARY KEY AUTO_INCREMENT
	, ORIGIN_FILE_NAME VARCHAR(100)  # 원본 파일명
	, UPLOAD_FILE_NAME VARCHAR(100)  # 첨부된 파일명
	, IS_MAIN VARCHAR(1) NOT NULL  #대표 이미지 여부(Y,N)
	, BOOK_NUM INT NOT NULL REFERENCES SHOP_BOOK (BOOK_NUM) ON DELETE CASCADE
	# ON DELETE CASCADE : BOOK_NUM을 지우면(도서를 지우면) 해당 컬럼이 같이 삭제됨(이미지도 같이 삭제)
)





UPDATE SHOP_MEMBER
SET 
	MEM_EMAIL = 'manager'
	, MEM_PW = '1111'
	, MEM_ROLE = 'MANAGER'
WHERE MEM_EMAIL = 'mm@naver.com';

# 이미지
# 도서번호, 도서명, 도서가격, 해당 도서의 첨부된 파일 조회
SELECT
	B.BOOK_NUM
	, BOOK_TITLE
	, BOOK_PRICE
	, UPLOAD_FILE_NAME
FROM SHOP_BOOK B INNER JOIN BOOK_IMG I
ON B.BOOK_NUM = I.BOOK_NUM;
-- WHERE IS_MAIN = 'Y';


CREATE TABLE SHOP_CART (
	CART_NUM INT PRIMARY KEY AUTO_INCREMENT 							#장바구니번호
	, BOOK_NUM INT NOT NULL REFERENCES SHOP_BOOK (BOOK_NUM) ON DELETE CASCADE  #상품번호 
	, CART_CNT INT NOT NULL 											#장바구니에 담은 도서 수량 #장바구니에 담은 수량
	, MEM_EMAIL VARCHAR(50) NOT NULL REFERENCES SHOP_MEMBER (MEM_EMAIL) #장바구니 주인 Email 
	, CART_DATE DATETIME DEFAULT SYSDATE() 								#장바구니에 담은 날짜
);

SELECT * FROM SHOP_CART ORDER BY CART_DATE DESC;   #장바구니
SELECT * FROM SHOP_MEMBER; 						#고객정보
SELECT * FROM SHOP_BOOK;   						#도서정보
SELECT * FROM BOOK_CATEGORY; 					#카테고리3개
SELECT * FROM BOOK_IMG;	   						#도서이미지
SELECT * FROM SHOP_BUY;							#구매정보
SELECT * FROM BUY_DETAIL;						#구매정보(상세)


# 구매 정보 테이블
CREATE TABLE SHOP_BUY (
	BUY_NUM INT PRIMARY KEY AUTO_INCREMENT 					#구매번호
	, BUY_PRICE INT NOT NULL 								#총구매금액
	, MEM_EMAIL VARCHAR(50) NOT NULL REFERENCES SHOP_MEMBER (MEM_EMAIL) #구매자 Email
	, BUY_DATE DATETIME DEFAULT SYSDATE() 					#구매일
);

# 구매 상세 정보 테이블
CREATE TABLE BUY_DETAIL (
	BUY_DETAIL_NUM INT PRIMARY KEY AUTO_INCREMENT 			#구매 상세 번호
	, BOOK_NUM INT NOT NULL REFERENCES SHOP_BOOK (BOOK_NUM) #상품번호
	, BUY_CNT INT NOT NULL 									#구매수량
	, BUY_NUM INT NOT NULL  REFERENCES SHOP_BUY (BUY_NUM) 	#구매번호
);



INSERT INTO SHOP_BUY VALUES (1,50000, 'bbb@naver.com', SYSDATE());
INSERT INTO BUY_DETAIL VALUES (1, 1, 3, 1);
INSERT INTO BUY_DETAIL VALUES (2, 2, 2, 1);

INSERT INTO SHOP_BUY VALUES (2,100000, 'bbb@naver.com', SYSDATE());
INSERT INTO BUY_DETAIL VALUES (3, 3, 3, 2);
INSERT INTO BUY_DETAIL VALUES (4, 1, 2, 2);
INSERT INTO BUY_DETAIL VALUES (5, 5, 4, 2);


DELETE FROM SHOP_BUY;
































